name: "git-publish-generated-branch"
description: "create & update derived git branches for hosting generated content"

inputs:
  ARGS:
    description: "args to pass to the git-publish-generated-branch CLI"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - run: echo "action_ref = ${{ github.action_ref }}, action_path = ${{ github.action_path }}, base_ref = ${{ github.base_ref }}."
      shell: bash
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: kiprasmel/git-publish-generated-branch
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # ref: ${{ github.action_ref }}
        ref: ${{ github.base_ref }}
        # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
        path: $RUNNER_TOOL_CACHE/git-publish-generated-branch

    - run: $RUNNER_TOOL_CACHE/git-publish-generated-branch/git-publish-generated-branch ${{ inputs.ARGS }}
      shell: bash
